version: "3"
services: 
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    
  app:
    image: gs-messaging-rabbitmq
    ports:
       - 8080:8080
    environment:
       - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
       - rabbitmq